name: build-dap-query-js
on:
  push:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:
jobs:
  verify-build:
    - uses: actions/checkout@v2.1.0
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g gulp
      - run: ls -a
      - run: pwd
      - run: cd ..
      - run: npm install
      - run: gulp process-all